### ISSUE TITLE
Redundant Queueable Execution

### ISSUE THREAD

**Issue by tshevchuk** [ytiq/apex-queueable-wrapper#1]
Use case:
* Enqueue single Queueable

Expected: only single Queueable job is executed to process the Queueable
Actual: Two Queueable jobs are executed. The first one calls `work()` method, the second one just checks `this.chain.isEmpty()` and exits.

**Comment by ytiq** [comment]
yes, you are right, thanks.

Will fix it now.

Not used to Issues being created here)

**Comment by ytiq** [comment]
@tshevshuk should be fixed now
